apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: techshack176/devops-scrapper-backend:cc336dd6c398b5fc73adeeafaa68e287871b0eb5
          ports:
            - containerPort: 8000  # Use a different port for FastAPI
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000  # Expose on a different port
      targetPort: 8000